name: End-to-end tests
on: [push]
jobs:
  cypress-eslint-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctlyand run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      # Run Eslint checks
      - name: Eslint run
        run: ./node_modules/.bin/eslint --ext js,jsx src
